<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2001, Zikula Development Team
 * @link http://www.zikula.org
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 *
 * @package TNGz
 * @url http://code.zikula.org/tngz
 * @license http://www.gnu.org/copyleft/gpl.html
 *
 * @original author Cas Nuy
 * @author Wendel Voigt
 * @version $Id$
 */

function TNGz_Placesblock_info()
{
    return array(
        'text_type'      => 'Placesblock',
        'text_type_long' => 'Places',
        'module'         => 'TNGz',
        'allow_multiple' => true,
        'form_content'   => false,
        'form_refresh'   => true,
        'show_preview'   => true

    );
}

function TNGz_Placesblock_init()
{
    // Security
    pnSecAddSchema('TNGz:Placesblock:', 'Block title::');
}

function TNGz_Placesblock_display($blockinfo)
{

    if( !pnSecAuthAction( 0, 'TNGz:Placesblock:', "$blockinfo[title]::", ACCESS_READ ) )
        return false;

    if( !pnModAPILoad('TNGz','user',true) ) {
        return false;
    }

    $userlanguage = pnUserGetLang();  //get the user's language

    // Get variables from content block
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['top'])  || !is_numeric($vars['top'])) {
        $vars['top'] = "10";
    }
    if (empty($vars['cols']) || !is_numeric($vars['cols'])) {
        $vars['cols']  = "1";
    }
    if (!isset($vars['intro'][$userlanguage])) {
        $vars['intro'][$userlanguage] = '';
    }
    $valid_stypes = array('list', 'table');  // first in list is the default
    $stype = (in_array($vars['stype'], $valid_stypes))? $vars['stype'] : $valid_stypes[0];
    
    $valid_sorts = array('alpha', 'rank');  // first in list is the default
    $sort = (in_array($vars['sort'], $valid_sorts))? $vars['sort'] : $valid_sorts[0];
    

    // Can turn off caching by using the following
    if ( $vars['usecache'] == 0 ) {
        $zcaching = false;
    } else {
        $zcaching = true;
    }

    // Create output object
    // Note that for a block the corresponding module must be passed.
    $pnRender = pnRender::getInstance('TNGz', $zcaching);

    PageUtil::addVar('stylesheet', ThemeUtil::getModuleStylesheet('TNGz'));

    $pnRender->assign('top',   $vars['top']);
    $pnRender->assign('cols',  $vars['cols']);
    $pnRender->assign('stype', $vars['stype']);
    $pnRender->assign('sort',  $vars['sort']);
    $pnRender->assign('intro', $vars['intro'][$userlanguage]);

    // Populate block info and pass to theme
    $blockinfo['content'] = $pnRender->fetch('TNGz_block_Places.htm');

    return themesideblock($blockinfo);
}

function TNGz_Placesblock_modify($blockinfo)
{

    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['top'])  || !is_numeric($vars['top'])) {
        $vars['top'] = "10";
    }
    if (empty($vars['cols']) || !is_numeric($vars['cols'])) {
        $vars['cols']  = "1";
    }

    if (!isset($vars['intro'])) {
        $vars['intro'] = array();
    }
    Loader::loadClass('LanguageUtil');
    $languages = LanguageUtil::getLanguages();
    // make sure each language has an initial value
    foreach($languages as $lang) {
        if (!array_key_exists($lang, $vars['intro'])) {
            $vars['intro'][$lang] = '';
        }
    }

    $validstypes = array('list', 'table');  // first in list is the default
    $stype = (in_array($vars['stype'], $validstypes))? $vars['stype'] : $validstypes[0];
    
    $validsorts = array('alpha', 'rank');  // first in list is the default
    $sort = (in_array($vars['sort'], $validsorts))? $vars['sort'] : $validsorts[0];

    // Create output object
    $pnRender =& new pnRender('TNGz');

    // As Admin output changes often, we do not want caching.
    $pnRender->caching = false;

    // assign the approriate values
    $pnRender->assign('stypelist', array( 'table' => pnVarPrepHTMLDisplay(_TNGZ_TABLE),
                                          'list'  => pnVarPrepHTMLDisplay(_TNGZ_LIST)
                                        ) );
    $pnRender->assign('sortlist', array(  'rank'  => pnVarPrepHTMLDisplay(_TNGZ_BYOCCURRENCE),
                                          'alpha' => pnVarPrepHTMLDisplay(_TNGZ_SORTEDALPHA)
                                        ) );

    $pnRender->assign('top',      $vars['top']);
    $pnRender->assign('cols',     $vars['cols']);
    $pnRender->assign('stype',    $vars['stype']);
    $pnRender->assign('sort',     $vars['sort']);
    $pnRender->assign('intro',    $vars['intro']);

    // Return the output that has been generated by this function
    return $pnRender->fetch('TNGz_block_Places_modify.htm');
}

function TNGz_Placesblock_update($blockinfo)
{
    //Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // alter the corresponding variable
    $vars['top']   = FormUtil::getPassedValue('top',    10,      'POST');
    $vars['cols']  = FormUtil::getPassedValue('cols',    1,      'POST');
    $vars['stype'] = FormUtil::getPassedValue('stype', 'list',   'POST');
    $vars['sort']  = FormUtil::getPassedValue('sort',  'alpha',  'POST');
    $vars['intro'] = FormUtil::getPassedValue('intro',  null,    'POST');

    // write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

    return $blockinfo;
}