<?php
/**
 * Zikula Application Framework
 *
 * @copyright  (c) Zikula Development Team
 * @link       http://www.zikula.org
 * @version    $Id$
 * @license    GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @author     Wendel Voigt
 * @category   Zikula_Extension
 * @package    Content
 * @subpackage TNGz
 */

/**
 * the main administration function
 */
function TNGz_admin_main()
{
    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing.  For the
    // main function we want to check that the user has at least edit privilege
    // for some item within this component, or else they won't be able to do
    // anything and so we refuse access altogether.  The lowest level of access
    // for administration depends on the particular module, but it is generally
    // either 'edit' or 'delete'
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_EDIT)) {
        $dom = ZLanguage::getModuleDomain('TNGz');
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_main.htm');
}

/**
 * This is a standard function to modify the configuration parameters of the
 * module
 */
function TNGz_admin_modifyconfig()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    // Get the TNG configuration information (false if there is a problem)
    $TNG = pnModAPIFunc('TNGz','user','TNGconfig');

    // *****************************************************
    // Check to be sure we can get to the TNG information
    // and check to make sure the rootpath is set correctly
    // *****************************************************
    $TNG_config     = false;
    $TNG_found      = __('TNG files Not Found', $dom);
    $TNG_foundimage = 'error.gif';

    $TNG_checkpath     = dirname($TNG['configfile']) . "/";
    $TNG_rootpath      = false;
    $TNG_rootpathsay   = __('TNG Root Path is not correct!', $dom) . " ". $TNG_checkpath;
    $TNG_rootpathimage = 'error.gif';


    if ($TNG) {
        $TNG_config        = true;
        $TNG_found         = __('TNG files Found', $dom);
        $TNG_foundimage    = 'button_ok.gif';

        if ( $TNG['rootpath'] ==  $TNG_checkpath ) {
            $TNG_rootpath      = true;
            $TNG_rootpathsay   = __('TNG Root Path is correct!', $dom);
            $TNG_rootpathimage = 'button_ok.gif';
        }
    }

    // *****************************************************
    // Get TNG version and make sure it is the same as last time
    // *****************************************************
    $TNG_versioncheck = false;
    $TNG_version      = ($TNG['tng_version'])? $TNG['tng_version'] :__('Unknown', $dom);
    $TNG_versionsay   = __('TNGz is not in sync with TNG version. Please update. Found new TNG Version. Changed from', $dom);
    $TNG_versionimage = 'error.gif';
    $TNG_versionlast  =  pnModGetVar('TNGz', '_version');

    if ( ($TNG_version == $TNG_versionlast) && ($TNG_version != __('Unknown', $dom)) ) {
        $TNG_versioncheck = true;
        $TNG_versionsay  = __('TNGz is in sync with TNG Version', $dom);
        $TNG_versionimage  = 'button_ok.gif';
    }
    
    // Get TNGz module information
    $ModName = pnModGetName();
    $ModInfo = pnModGetInfo(pnModGetIDFromName($ModName));

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render = & pnRender::getInstance('TNGz', false);
    
    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    $row = array();

/*
    These are no longer used.
    $_config   = pnVarCleanFromInput('_config');
    $_db       = pnVarCleanFromInput('_db');
    $_mail     = pnVarCleanFromInput('_mail');
    $_basepath = pnVarCleanFromInput('_basepath');
    $_debug    = pnVarCleanFromInput('_debug');
*/

    // What version of TNGz
    $render->assign('TNGzVersion', $ModInfo['version']);
    $render->assign('TNGzName',    $ModInfo['name']);

    // check password hash - TNG uses MD5 and should be used in Zikula
    $ZikulaHash   = pnModGetVar('Users', 'hash_method');
    $TNGhash      = ($TNG['use_password_type']) ? $TNG['password_type'] : 'md5';
    $TNGcanChange = ($TNG['use_password_type']) ? true : false;
    $HashCheck    = ($ZikulaHash == $TNGhash )? true : false ;
    $render->assign('hashcheck'     , $HashCheck);
    $render->assign('hashZikula'    , $ZikulaHash);
    $render->assign('hashTNG'       , $TNGhash);
    $render->assign('hashTNGchange' , $TNGcanChange);

    // Is the TNG setup found?
    $render->assign('tngconfig'     ,$TNG_config);
    $render->assign('tngfound'     , $TNG_found);
    $render->assign('tngfoundimage', $TNG_foundimage);

    // Is the TNG $rootpath set to the same directory
    $render->assign('tngrootpath'     , $TNG_rootpath);
    $render->assign('tngrootpathsay'  , $TNG_rootpathsay);
    $render->assign('tngrootpathimage', $TNG_rootpathimage);

    // Is the TNG version the same as last time
    $render->assign('TNG_version'       , $TNG_version);
    $render->assign('TNG_versioncheck'  , $TNG_versioncheck);
    $render->assign('TNG_versionsay'    , $TNG_versionsay);
    $render->assign('TNG_versionimage'  , $TNG_versionimage);
    $render->assign('TNG_versionlast'   , $TNG_versionlast);


    // Allow non-logged in Zikula users as a Guest
    $render->assign('tngguest', pnModGetVar('TNGz', '_guest'));

    // If non-logged in Zikula users as a Guest, under what name?
    $render->assign('tngguestname', pnModGetVar('TNGz', '_gname'));

    // Create TNG users from Zikula user information
    $render->assign('tngusers', pnModGetVar('TNGz', '_users'));

    // Can a created user see Living?
    $render->assign('tngliving', pnModGetVar('TNGz', '_living'));

    /*! Email Filter Options */
    $email_options = array( __('No (faster)', $dom),
                            __('Yes', $dom),
                            __('Yes, and make plain email addresses clickable', $dom)
                          );
    $email_values = array( "N", "E", "A" );
    $render->assign('tngemailoptions', $email_options );
    $render->assign('tngemailvalues',  $email_values );
    $render->assign('tngemail', pnModGetVar('TNGz', '_email'));

    // Can a created user download GEDCOMs?
    $render->assign('tnggedcom', pnModGetVar('TNGz', '_gedcom'));

    // Can a created user see LDS information?
    $render->assign('tnglds', pnModGetVar('TNGz', '_lds'));

    // For created users, Sync TNG info with Zikula info?
    $render->assign('tngsync', pnModGetVar('TNGz', '_sync'));

    // For TNGz homepage for TNG index
    $render->assign('tngzhomepage', pnModGetVar('TNGz', '_homepage'));

    // For TNGz caching options
    $cache_db_options = array( __('Off', $dom), __('On', $dom));
    $cache_db_values  = array(    "0"    ,   "1"     );
    $render->assign('tngzcachedb',        pnModGetVar('TNGz', '_cachedb'));
    $render->assign('tngzcachedboptions', $cache_db_options);
    $render->assign('tngzcachedbvalues',  $cache_db_values );

    $minute = 60; // 60 seconds
    $hour   = 60 * $minute;
    $day    = 24 * $hour;
    $cache_sec_options[] =         __('Off',     $dom) ; $cache_sec_values[] =  0;
    $cache_sec_options[] = '30 ' . __('minutes', $dom) ; $cache_sec_values[] = 30 * $minute;
    $cache_sec_options[] = ' 1 ' . __('hour',    $dom) ; $cache_sec_values[] =  1 * $hour;
    $cache_sec_options[] = ' 2 ' . __('hours',   $dom) ; $cache_sec_values[] =  2 * $hour;
    $cache_sec_options[] = ' 4 ' . __('hours',   $dom) ; $cache_sec_values[] =  4 * $hour;
    $cache_sec_options[] = '12 ' . __('hours',   $dom) ; $cache_sec_values[] = 12 * $hour;
    $cache_sec_options[] = ' 1 ' . __('day',     $dom) ; $cache_sec_values[] =  1 * $day;
    $cache_sec_options[] = ' 2 ' . __('days',    $dom) ; $cache_sec_values[] =  2 * $day;
    $cache_sec_options[] = ' 3 ' . __('days',    $dom) ; $cache_sec_values[] =  3 * $day;
    $cache_sec_options[] = ' 4 ' . __('days',    $dom) ; $cache_sec_values[] =  4 * $day;
    $cache_sec_options[] = ' 5 ' . __('days',    $dom) ; $cache_sec_values[] =  5 * $day;
    $cache_sec_options[] = ' 6 ' . __('days',    $dom) ; $cache_sec_values[] =  6 * $day;
    $cache_sec_options[] = ' 7 ' . __('days',    $dom) ; $cache_sec_values[] =  7 * $day;

    $render->assign('tngzcachesec', pnModGetVar('TNGz', '_cachesec'));
    $render->assign('tngzcachesecoptions', $cache_sec_options );
    $render->assign('tngzcachesecvalues',  $cache_sec_values  );    

    if (pnModGetVar('TNGz', '_cachedb') != 0 && pnModGetVar('TNGz', '_cachesec') !=0 ) {
        pnModAPIFunc('TNGz','user','CacheInit');  // If needed, initialize the cache
    }

    $cache_exists = (pnModAPIFunc('TNGz','user','CacheExists'))? "1" : "0";
    $render->assign('tngzcacheexists',  $cache_exists  );

    // Primary Person ID
    // Note: To uniquely identify a person, need personID and gedcom/tree name
    $personID    = pnModGetVar('TNGz', '_personID',   '' );
    $person_tree = pnModGetVar('TNGz', '_persontree', '0');
    $treeoptions[] = __('Off', $dom);
    $treevalues[]  = "0";
        
    // Get the possible trees 
    if ($TNG){
        PageUtil::AddVar('javascript', pnGetBaseURL().$TNG['directory'].'/'.$TNG['js_dir'].'net.js');
        PageUtil::AddVar('javascript', 'javascript/ajax/prototype.js');
        PageUtil::AddVar('javascript', 'javascript/ajax/scriptaculous.js');
        PageUtil::AddVar('javascript', pnGetBaseURL().$TNG['directory'].'/'.$TNG['js_dir'].'net.js');
        PageUtil::AddVar('javascript', pnGetBaseURL().$TNG['directory'].'/'.$TNG['js_dir'].'litbox.js');
        
        $TNG_conn = pnModAPIFunc('TNGz','user','DBconnect');
        $query = "SELECT gedcom, treename FROM ".$TNG['trees_table']." ORDER BY treename";
        if ($result = $TNG_conn->Execute($query) ) {
            if ($result->RecordCount() > 0) {
                for (; !$result->EOF; $result->MoveNext()) {
                    $row = $result->fields;
                    $treeoptions[] = $row['treename'];
                    $treevalues[]  = $row['gedcom'];
                }
            }
            $result->Close();
        }       
    }
    $person = pnModAPIFunc('TNGz','user','getperson', array('id'=> $personID, 'tree'=> $person_tree));
    $personmsg = (!$person) ? "" : $personID . " = " . $person['fullname'];
    $render->assign('tngzid',            $personID    );
    $render->assign('tngzidtree',        $person_tree );
    $render->assign('tngzidtreeoptions', $treeoptions );
    $render->assign('tngzidtreevalues',  $treevalues  );
    $render->assign('tngzidname',        $personmsg   );

    // TNG location
    $render->assign('tngmodule'    , pnModGetVar('TNGz', '_loc'));
    $render->assign('zikula'       , dirname(dirname(dirname(realpath(__FILE__))))."/" );

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_modifyconfig.htm');
}

function TNGz_admin_updateconfig()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    // Security check - important to do this as early as possible to avoid
    // potential security holes or just too much wasted processing
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    // Get parameters from whatever input we need.  All arguments to this
    // function should be obtained from pnVarCleanFromInput(), getting them
    // from other places such as the environment is not allowed, as that makes
    // assumptions that will not hold in future versions of Zikula
    // Get parameters from whatever input we need.
    $_loc         = FormUtil::getPassedValue('tngmodule',    null, 'REQUEST');
    $_guest       = FormUtil::getPassedValue('tngguest',     null, 'REQUEST');
    $_users       = FormUtil::getPassedValue('tngusers',     null, 'REQUEST');
    $_living      = FormUtil::getPassedValue('tngliving',    null, 'REQUEST');
    $_email       = FormUtil::getPassedValue('tngemail',     null, 'REQUEST');
    $_gedcom      = FormUtil::getPassedValue('tnggedcom',    null, 'REQUEST');
    $_lds         = FormUtil::getPassedValue('tnglds',       null, 'REQUEST');
    $_sync        = FormUtil::getPassedValue('tngsync',      null, 'REQUEST');
    $_gname       = FormUtil::getPassedValue('tngguestname', null, 'REQUEST');
    $_version     = FormUtil::getPassedValue('tngversion',   null, 'REQUEST');
    $_homepage    = FormUtil::getPassedValue('tngzhomepage', null, 'REQUEST');
    $_cachedb     = FormUtil::getPassedValue('tngzcachedb',  null, 'REQUEST');
    $_cachesec    = FormUtil::getPassedValue('tngzcachesec', null, 'REQUEST');
    $_personid    = FormUtil::getPassedValue('tngzid',       null, 'REQUEST');
    $_personidtree= FormUtil::getPassedValue('tngzidtree',   null, 'REQUEST');

    /*
    $_config   = pnVarCleanFromInput('_config');
    $_db       = pnVarCleanFromInput('_db');
    $_debug    = pnVarCleanFromInput('_debug');
    $_mail     = pnVarCleanFromInput('_mail');
    $_basepath = pnVarCleanFromInput('_basepath');
    */

    // Confirm authorisation code.  This checks that the form had a valid
    // authorisation code attached to it.  If it did not then the function will
    // proceed no further as it is possible that this is an attempt at sending
    // in false data to the system
    if (!SecurityUtil::confirmAuthKey()) {
        LogUtil::registerStatus(__("Invalid 'authkey':  this probably means that you pressed the 'Back' button, or that the page 'authkey' expired. Please refresh the page and try again.", $dom));
        pnRedirect(pnModURL('TNGz', 'admin', 'main'));
        return true;
    }

    // Update module variables.
    if (empty($_loc)) { $_loc = ""; }
        pnModSetVar('TNGz', '_loc'      , $_loc);

    if (empty($_guest)) { $_guest = 0; }
        pnModSetVar('TNGz', '_guest'    , $_guest);

    /*! this is the default guest user name to be used with TNG */
    if (empty($_gname) || ($_gname=="") ){ $_gname = __('Guest', $dom /*! the default guest user name to be used with TNG */);}
        pnModSetVar('TNGz', '_gname'    , $_gname);

    if (empty($_users)) { $_users = 0; }
        pnModSetVar('TNGz', '_users'    , $_users);

    if (empty($_living)) { $_living = 0; }
        pnModSetVar('TNGz', '_living'   , $_living);

    if (empty($_email)) { $_email = __('No (faster)', $dom); }
        pnModSetVar('TNGz', '_email'   , $_email);

    if (empty($_gedcom)) { $_gedcom = 0; }
        pnModSetVar('TNGz', '_gedcom'   , $_gedcom);

    if (empty($_lds)) { $_lds = 0; }
        pnModSetVar('TNGz', '_lds'      , $_lds);

    if (empty($_sync)) { $_sync = 0; }
        pnModSetVar('TNGz', '_sync'     , $_sync);

    if (empty($_version) || ($_version=="") ){ $_version = __('Unknown', $dom);}
        pnModSetVar('TNGz', '_version'  , $_version);
        
    if (empty($_homepage)) { $_homepage = 0; }
        pnModSetVar('TNGz', '_homepage'     , $_homepage);
        
    if (empty($_cachedb)) { $_cachedb = 0; }
        pnModSetVar('TNGz', '_cachedb'     , $_cachedb);
        
    if (empty($_cachesec)) { $_cachesec = 0; }
        pnModSetVar('TNGz', '_cachesec'     , $_cachesec);
        
    if (empty($_personid)) { $_personid = ""; }
    $_personid = trim($_personid);
    if (!preg_match("/^[a-zA-Z]+[0-9]+$/",$_personid) ) {$_personid="";}
    pnModSetVar('TNGz', '_personID'     , $_personid);

    if (empty($_personidtree)) { $_personidtree = "0"; }
        pnModSetVar('TNGz', '_persontree'     , $_personidtree);

/*
    pnModSetVar('TNGz', '_config'   , $_config);
    pnModSetVar('TNGz', '_db'       , $_db);
    pnModSetVar('TNGz', '_mail'     , $_mail);
    pnModSetVar('TNGz', '_basepath' , $_basepath);
    pnModSetVar('TNGz', '_debug'    , $_debug);
*/

    //////////////////////////////////////////////////////////////////
    // Scan the TNG php files to record all the global variables
    /////////////////////////////////////////////////////////////////
    // Note: the TNG location informaiton was saved above, so we can use it now
    // Also, we do this every time to make sure we have the latest, just in case files are changed
    $TNG = pnModAPIFunc('TNGz','user','GetTNGpaths');

    if ($TNGglobals = pnModAPIFunc('TNGz','user','GetTNGglobals', array('dir' => $TNG['SitePath']."/".$TNG['directory']))) {
        pnModSetVar('TNGz', '_globals'     , $TNGglobals);
    }

    // the module configuration has been updated successfuly
    pnSessionSetVar('statusmsg', __('Done! Module configuration updated.', $dom));

    // This function generated no output, and so now it is complete we redirect
    // the user to an appropriate page for them to carry on their work
    pnRedirect(pnModURL('TNGz', 'admin', 'main'));

    // Return
    return true;
}

function TNGz_admin_TNGadmin()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    if (!pnUserLoggedIn()) {
        // Must be logged in to even have a chance at getting to the administration page
        pnRedirect(pnModURL('Users','user','loginscreen')) ;
    }

    if (!$url=pnModAPIFunc('TNGz','user','GetTNGurl') ) {
        return LogUtil::registerError("Error accessing TNG config file.");
    }

    // Get TNGz module information
    $pnTNGmodinfo = pnModGetInfo(pnModGetIDFromName('TNGz'));

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    $render->assign('TNGzURL'      , $url);
    $render->assign('TNGzVersion'  , $pnTNGmodinfo['version'] );
    $render->assign('TNGzName'     , $pnTNGmodinfo['name']);

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_tngadmin.htm');
}

function TNGz_admin_Instruct()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    // Get TNGz module information
    $pnTNGmodinfo = pnModGetInfo(pnModGetIDFromName('TNGz'));

    $helpfile = 'modules/'.DataUtil::formatForOS($pnTNGmodinfo['directory']).'/'.DataUtil::formatForOS($pnTNGmodinfo['help']);
    if (file_exists($helpfile)) {
        $helpfile = "<pre>" . implode('',file($helpfile)) . "</pre>";
        $helpfile = DataUtil::formatForDisplayHTML($helpfile);
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    $render->assign('TNGzVersion'  , $pnTNGmodinfo['version'] );
    $render->assign('TNGzName'     , $pnTNGmodinfo['name']);
    $render->assign('helpfile'     , $helpfile);

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_install.htm');

}

function TNGz_admin_Info()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    // Get TNGz module information
    $pnTNGmodinfo = pnModGetInfo(pnModGetIDFromName('TNGz'));
    $pnTNGmodvars = pnModGetVar('TNGz');


    $changelog = 'modules/'.DataUtil::formatForOS($pnTNGmodinfo['directory']).'/'.DataUtil::formatForOS($pnTNGmodinfo['changelog']);
    if (file_exists($changelog)) {
        $changelog = "<pre>" . implode('',file($changelog)) . "</pre>";
        $changelog = DataUtil::formatForDisplayHTML($changelog);
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    $render->assign('TNGzVersion'  , $pnTNGmodinfo['version'] );
    $render->assign('TNGzName'     , $pnTNGmodinfo['name'] );

    $render->assign('changelog'  , $changelog );

    foreach ($pnTNGmodinfo as $key => $value) {
        $debuglist[] = array( 'key' => $key, 'value' => $value );
    }
    foreach ($pnTNGmodvars as $key => $value) {
        $debuglist[] = array( 'key' => $key, 'value' => $value );
    }
    $render->assign('debuglist'  , $debuglist);

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_info.htm');

}

function TNGz_admin_cachedelete()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_EDIT)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    $success = pnModAPIFunc('TNGz','user','CacheDelete');
    
    // the module configuration has been updated successfuly
    $msg = ($success) ? __('Cache cleared', $dom) : __('Error clearing cache', $dom);
    pnSessionSetVar('statusmsg', $msg);

    // This function generated no output, and so now it is complete we redirect
    // the user to an appropriate page for them to carry on their work
    pnRedirect(pnModURL('TNGz', 'admin', 'main'));
    
    // Return
    return true;
}

function TNGz_admin_userlog()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    $pnTNGmodinfo = pnModGetInfo(pnModGetIDFromName('TNGz'));

    $userlog = 'genlog.txt';

    if (file_exists($userlog)) {
        $userlog = "<pre>" . implode('',file($userlog)) . "</pre>";
        $userlog = DataUtil::formatForDisplayHTML($userlog);
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');

    $render->assign('TNGzVersion'  , $pnTNGmodinfo['version'] );
    $render->assign('TNGzName'     , $pnTNGmodinfo['name'] );
    $render->assign('userlog'      , $userlog );

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_userlog.htm');

}

function TNGz_admin_adminlog()
{
    $dom = ZLanguage::getModuleDomain('TNGz');
    
    if (!SecurityUtil::checkPermission('TNGz::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerError(__('Sorry! No authorization to access this module.', $dom));
    }

    $pnTNGmodinfo = pnModGetInfo(pnModGetIDFromName('TNGz'));
    
    // Get TNGz module information
    $TNG = pnModAPIFunc('TNGz','user','TNGconfig');

    $adminlog = $TNG['TNGpath'].'/'.$TNG['admin_dir'].'adminlog.txt';

    if (file_exists($adminlog)) {
        $adminlog = "<pre>" . implode('',file($adminlog)) . "</pre>";
        $adminlog = DataUtil::formatForDisplayHTML($adminlog);
    }

    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $render =& new pnRender('TNGz');
    
    $render->assign('TNGzVersion'  , $pnTNGmodinfo['version'] );
    $render->assign('TNGzName'     , $pnTNGmodinfo['name'] );
    $render->assign('adminlog'     , $adminlog );

    // As Admin output changes often, we do not want caching.
    $render->caching = false;

    // Return the output that has been generated by this function
    return $render->fetch('TNGz_admin_adminlog.htm');

}
